---
- name: check for existing configuration under an interface and update if not present 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: get all configured VLANS 
        ios_facts:
        register: output_interfaces
        
      - name: check if IP helper is configured 
        ios_command:
          commands: 'sh run interface {{ item.key }}'
        with_dict: "{{ output_interfaces.ansible_facts.ansible_net_interfaces }}"
        register: output
      - set_fact: 
          check_helper_add: "{{ output_interfaces.results }}"
          
      - name: configuration commands on cisco device
        ios_config:
            lines: 
              - ip helper-address 172.26.0.1
              - ip helper-address 172.16.0.1
            parents: "interface {{ item.key }}"
        with_dict: "{{ output_interfaces.ansible_facts.ansible_net_interfaces }}"
        when: '" ip helper-address 172.26.0.1" not in check_helper_add[0].stdout[0]'
...
