---
#Bulk configuration deploymenton a cisco IOS device - contributed by KA
- name: configure cisco devices 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
    - name: configuration commands on cisco device
      ios_config:
        multiline_delimiter: "\n"
        lines:
          - "{{ Commands_enter }}"
 
...
