---
- name: check for existing description under an interface and update if present 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: get IOS facts 
        ios_facts:
        register: device_ios_facts
          
      - name: configuration commands to be added on cisco device
        ios_config:
            lines: 
              - "{{ provided_config_line }}"
            parents: "interface {{ item.key }}"
        with_dict: "{{ device_ios_facts.ansible_facts.ansible_net_interfaces }}"
        when: 
          - 'item.key is regex("Vlan.*")'
          - 'item.value["description"] == config_to_be_checked'
...
