---
- name: check for existing configuration under an interface and update if not present 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: get IOS facts 
        ios_facts:
        register: device_ios_facts
      - name: check if IP helper is configured 
        ios_command:
          commands: 'sh run interface {{ item.key }}'
        with_dict: "{{ device_ios_facts.ansible_facts.ansible_net_interfaces }}"
        register: interface_running_output
      - set_fact: 
          check_config_arg: "{{ interface_running_output.results }}"
      - name: configuration commands on cisco device
        ios_config:
          lines: 
              - "{{ config_to_add }}"
          parents: "interface {{ item.key }}"
        with_dict: "{{ device_ios_facts.ansible_facts.ansible_net_interfaces }}"
        when: 'config_to_check not in check_config_arg[0].stdout[0]'
...
