---

- name: Configuration update on an Interface 
  connection: network_cli
  gather_facts: false

  hosts: all
  
- name: configure ip helpers on multiple interfaces
  ios_config:
    lines:
      ip helper-address 172.26.3.8
    parents: "{{ item }}"
    
  with_items: 
    interface GigabitEthernet1
....
