---
- name: check for existing configuration under an interface and update if not present 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: get all configured VLANS 
        ios_command:
          commands: 'sh ip int br | i Vlan'
        register: output_vlans
      - set_fact: 
          output_vlans: "{{ output.stdout[0] }}"
          
      - name: check if IP helper is configured 
        ios_command:
          commands: 'sh run interface {{ item }}'
        with_items: 
          - Vlan1
        register: output
      - set_fact: 
          check_helper_add: "{{ output.results }}"
          
      - name: configuration commands on cisco device
        ios_config:
            lines: 
              - ip helper-address 172.26.0.1
              - ip helper-address 172.16.0.1
            parents: "interface {{ item }}"
        with_items: 
          - Vlan1
        when: '" ip helper-address 172.26.0.1" not in check_helper_add[0].stdout[0]'
...
