---
- name: check for existing configuration under an interface and update if present 
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: get IOS facts 
        ios_facts:
        register: device_ios_facts
      - name: Get running configuration from all interfaces 
        ios_command:
          commands: 'sh run interface {{ item.key }}'
        with_dict: "{{ device_ios_facts.ansible_facts.ansible_net_interfaces }}"
        register: interface_running_output
      - set_fact: 
          check_config_arg: "{{ interface_running_output.results }}"
      - name: Deploy configuration commands on cisco device if command is present
        ios_config:
          lines: 
              - "{{ config_to_add }}"
          parents: "interface {{ item.item.key }}"
        loop: "{{ check_config_arg }}"
        when: 
          - 'config_to_check in item.stdout[0]'
...
