---
# Configuration check - compliance policy file- contributed by KA
# Here the check is agains the "show run" output from the device and as long as the line is present in the config this script will report the device to be complaint 
# and hence may not accurately present deterministic results for those querries.

- name: Check if the device satisfies compliance requirements
  connection: network_cli
  display_skipped_hosts: no
  gather_facts: false
  hosts: all

  tasks:
      - name: show output of any command entered by the user
        ios_command:
          commands:
             - show run
        register: device_running_config
      - set_fact: 
          check_config: "{{ device_running_config.stdout[0] }}"
      
      - name: Reports COMPLIANT if the line exists in the running configuration else Skip 
        debug:
            msg: "Configuration line is present. {{ inventory_hostname }} is COMPLIANT!"
        when: 'item in check_config'
        with_items: "{{ provided_config_line.split('\n') }}"
        
      - name: Reports NOT COMPLIANT if the line doesn't exist in the running configuration else Skip 
        debug:
            msg: "CONFIGURATION LINE IS NOT PRESENT. {{ inventory_hostname }} IS NOT COMPLIANT!"
        when: 'item not in check_config'
        with_items: "{{ provided_config_line.split('\n') }}"

...
