---
#SNMP Cconfiguration check - compliance policy file- contributed by KA

- name: Check if the device satisfies SNMP compliance requirements
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: show output of any command entered by the user
        ios_command:
          commands:
             - show run
          wait_for:
            - result[0] contains "{{ item }}"    
        loop: provided_config_line
        
...
