---
#SNMP Cconfiguration check - compliance policy file- contributed by KA

- name: Check if the device satisfies SNMP compliance requirements
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
      - name: show output of any command entered by the user
        ios_command:
          commands:
             - show run
        register: device_running_config
      - set_fact: 
          check_config: "{{ device_running_config.stdout[0] }}"
      
      - name: check if user provided lines are present
        debug:
            msg: "Yes, configuration lines are present. The device is complaint!"
        when: '"{{ item }}" in  check_config'
        with_items: "{{ provided_config_line }}"
        debug:
            msg: "one or more configuration lines aren't present. The device is not complaint!"
            type: warning
        when: '"{{ item }}" not in  check_config'
        with_items: "{{ provided_config_line }}"
        
...
