---
- name: First Network Playbook show version
  connection: network_cli
  gather_facts: false

  hosts: all

  tasks:
    - name: show version
      ios_command:
        commands: show version

      register: output

    - name: show output
      debug:
        var: output.stdout


...
