---

- name: run any Show commands on Cisco devices
  connection: network_cli
  gather_facts: false
  
  hosts: all

  tasks:
    - name: show output of any command entered by the user
      ios_command:
        commands:
             - show {{ item }}
      with_items: "{{ command_input }}"

...
