---
- name: Playbook Backup configuration cisco IOS
  connection: network_cli
  gather_facts: false
  
  hosts: all
  
  tasks:
   - name: show run 
     ios_command:
       commands: show run
     register: config
   - name: save output to /var/lib/awx/projects/Tenfour-lab-devices 
     copy:
      content: "{{ config.stdout[0] }}"
      dest: "/var/lib/awx/projects/Tenfour-lab-devices/show_run_{{ inventory_hostname }}.txt"

...
